version: 1.0

jobs:
  build:
    docker:
      - image: circleci/node:8.17.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Build project
          command: yarn build
workflows:
  build_and_deploy:
    jobs:
      - build
