version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.2.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Build project
          command: yarn build
      - run:
          name: Install functions packages
          command: cd ./functions && yarn install
  deploy:
    docker:
      - image: cimg/node:22.2.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Build project
          command: yarn build
      - run:
          name: Install functions packages
          command: cd ./functions && yarn install
      - run:
          name: Installing Firebase-Tools
          command: yarn add firebase-tools
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

